added Course Form
makeopensource/devU pull request #31
Opened 2024-02-10 09:42 UTC by kevinzhong930

Created a form to add courses.

2024-02-13 04:49 UTC, jessehartloff requested changes
I was under the impression that the existing code would display all courses and that it only didn't because the DB was empty. I see now that that's not the case. Before moving forward, we'll need a way to see the courses/assignments that have been created

2024-02-13 04:49 UTC, jessehartloff commented on devU-client/src/components/pages/userCoursesListPage.tsx
> +        </div>
This says it's a button, but it displays as a plain blue-text link (At least in my browser). Can you make it render as actual button

2024-02-13 04:49 UTC, jessehartloff commented on devU-client/src/components/pages/coursesFormPage.tsx
> +//import styles from 'components/pages/coursesFormPage.scss'
Don't leave in commented out code. If it's not going to use, delete it

2024-02-13 04:49 UTC, jessehartloff commented on devU-client/src/components/pages/coursesFormPage.tsx
> +                setAlert({ autoDelete: false, type: 'error', message })
This alert is too small to contain error messages and it trims it with ellipses and no option to see the full message. Clicking just removes the message. I know you didn't build this feature and it's not part of this PR, but this should be addressed at some point in the future

2024-02-13 04:49 UTC, jessehartloff commented on devU-client/src/components/pages/coursesFormPage.tsx
> +            <TextField id='endDate' label='End Date' onChange={handleChange}/>
Please use date pickers for these. Manually typing dates in the correct format is nearly unusable

2024-02-13 08:04 UTC, kevinzhong930 commented
@jessehartloff I believe I pushed all the necessary changes... Hopefully

2024-02-15 05:13 UTC, jessehartloff approved these changes

2024-02-15 05:14 UTC, merged